# ~~~
# This file is part of the dune-xt-data project:
#   https://github.com/dune-community/dune-xt-data
# Copyright 2018 dune-xt-data developers and contributors. All rights reserved.
# License: Dual licensed as BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause) 
# or  GPL-2.0+ (http://opensource.org/licenses/gpl-license) 
# with "runtime exception" (http://www.dune-project.org/license.html)
# Authors:
#   Rene Milk (2018)
# ~~~

################################
# Dune module information file #
################################


#Name of the module
Module: dune-xt-data
Version: 18.10
Maintainer: rene.milk@wwu.de
#depending on
# dunecontrol only supports the operators "<=", ">=", "=" for version checks, no ranges and no "<", ">", "|", "&", so we duplicate dependencies to get a version range
Depends: dune-xt-common (>=18.10) dune-xt-common (<=18.10.99)
